### ISSUE TITLE
Prusa keeps timing out on gcode

### ISSUE THREAD

**Issue by yoyo42** [prusa3d/Prusa3D-Test-Objects#7]
I have a Mk3 with official Prusa firmware 3.5.1. I just downloaded the ECOR tower and tried to print it with Octoprint 1.3.10 via a Pi 3B+, but the printer keeps stalling and showing 'Full RX buffer' in the terminal window.

This happenes every 30-60s or so and takes longer to recover before arying on each time, then stops completely and Octoprint reports "Communication error:
There was a communication error while talking to your printer. Please consult the terminal output and octoprint.log for details. Error: Too many consecutive timeouts, printer still connected and alive?"

Example terminal output for a stop/restart:
====
Send: N1222 G1 Z6.000 F10200.000*2
Send: N1223 G4 S0*92
Recv: ok
Send: TMC_SET_STEP_E54
Recv: ok
Recv: ok
Send: N1224 G1 Z5.600 F10200.000*1
Send: N1225 G1 E0.80000 F2100.00000*36
Send: N1226 M204 S800*89
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: ok
[...]
Recv: tmc2130_goto_step 3 54 2 1000
Recv: ok
Send: N1228 G1 F900*78
Recv: ok
Send: N1229 G1 X137.275 Y117.275 E0.00203*89
Recv: ok
Send: N1230 G1 X112.725 Y117.275 E0.83099*92
Recv: ok
[...]
Send: N1231 G1 X112.725 Y92.725 E0.83099*97
Send: N1232 G1 X137.275 Y92.725 E0.83099*101
Recv: ok
Recv: ok
Send: N1233 G1 X137.275 Y117.155 E0.82693*84
Recv: ok
Recv: ok
Send: N1234 M204 S1000*99
Send: N1235 G1 F8160*116
Send: N1236 G1 X137.275 Y117.275 E-0.02934*119
Recv: Full RX Buffer
Recv: fsensor_autoload_check_start - autoload ENABLED
Recv: 
Communication timeout while printing, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
[...]
Recv: Error:Line Number is not Last Line Number+1, Last Line: 1231
Recv: Resend: 1232
Recv: ok
Send: N1234 M204 S1000*99
Send: N1235 G1 F8160*116
Send: N1236 G1 X137.275 Y117.275 E-0.02934*119
Recv: Full RX Buffer
Recv: fsensor_autoload_check_start - autoload ENABLED
Recv: 
Communication timeout while printing, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
[...]
Recv: Error:Line Number is not Last Line Number+1, Last Line: 1231
Recv: Resend: 1232
Recv: ok
Send: N1232 G1 X137.275 Y92.725 E0.83099*101
Recv: ok
Send: N1233 G1 X137.275 Y117.155 E0.82693*84
Recv: fsensor_autoload_check_stop - autoload DISABLED
Recv: 
Recv: ok
Send: N1234 M204 S1000*99
Recv: ok
Send: N1235 G1 F8160*116
Recv: ok
Send: N1236 G1 X137.275 Y117.275 E-0.02934*119
Recv: ok
[...]
Send: N1239 M117 12.50p  complete*108
Recv: ok
Send: N1240 M117 ETL 01h03m14s*63
Recv: ok
Send: N1241 M117 ETA 16 32 24 Day 22*30
Recv: ok
Send: N1242 M117 Good accuracy*47
Recv: ok
Send: N1243 G1 F8160*117
Recv: ok
Send: N1244 G1 X134.286 Y117.275 E-0.73066*117
Recv: ok
Send: N1245 G1 E-0.04000 F2100.00000*3
Recv: ok
Send: N1246 G1 Z6.200 F10200.000*2
Recv: ok
Send: N1247 G4 S0*94
Recv: echo:busy: processing
Recv: ok
Send: N1248 M117 12.55p  complete*111
Recv: ok
Send: TMC_SET_STEP_E56
Send: N1249 G1 Z5.800 F10200.000*4
Recv: tmc2130_goto_step 3 56 2 1000
Recv: ok
Send: N1250 G1 E0.80000 F2100.00000*38
Recv: ok
Send: N1251 M204 S800*89
Recv: ok
Send: N1252 G1 F900*67
Recv: ok
Send: N1253 G1 X137.275 Y117.275 E0.00406*87
Recv: ok
====

and also output from when it stops completely:

====
Send: N1848 G1 X137.275 Y117.275 E-0.02934*116
Recv: ok
Recv: ok
Recv: ok
Send: N1849 G1 F8160*117
Recv: ok
Send: N1850 G1 X134.286 Y117.275 E-0.73066*122
Recv: ok
Recv: ok
Send: N1851 G1 E-0.04000 F2100.00000*12
Send: N1852 G1 Z12.600 F10200.000*60
Recv: ok
Recv: ok
Send: N1853 G4 S0*81
Send: TMC_SET_STEP_E120
Send: N1854 G1 Z12.200 F10200.000*62
Send: N1855 G1 E0.80000 F2100.00000*41
Send: N1856 M204 S800*84
Recv: Full RX Buffer
No response from printer after 6 consecutive communication timeouts, considering it dead. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
Changing monitoring state from "Printing" to "Offline (Error: Too many consecutive timeouts, printer still connected and alive?)"
Connection closed, closing down monitor
====

**Comment by ahdchild** [comment]
I had the same issue with Octoprint. You should print from SD card

**Comment by yoyo42** [comment]
No longer an issue with more recent versions
